### ISSUE TITLE
sistemare

### ISSUE THREAD

**Issue by samirlegdah** [samirlegdah/Bluni#3]
@silvioalberto91 
- sistemare commenti codice
- scrivere funzione per controllare parametri
- scrivere funzione ajax per richiamare server
- crea in doc, una folder "screenUI", metti lo screen della sezione cerca quando è finita

**Comment by silvioalberto91** [comment]
@samirlegdah 
dove trovo doc?

**Comment by samirlegdah** [comment]
@silvioalberto91  Bluni/doc

**Comment by samirlegdah** [comment]
@silvioalberto91 ho visto, ora non c'è... creala pure tu e fai il commit ;)
